### ISSUE TITLE
Feature request: Node that detects when it was interrupted

### ISSUE THREAD

**Issue by TravisGesslein** [behavior3/behavior3js#1]
What about a node type (I guess this would be a decorator) that detects if it was interrupted (i.e., not executed in two successive evaluations of the tree in a row) and then calls some kind of "resume" function that can be overwritten by children? 

Example where this could be useful: In my game an entity walks along a path towards some goal, all of which is implemented in one sub tree in the behavior tree. But along the way, an enemy might come into sight and the entity might decide to fight that enemy instead of following the path, which is implemented in another sub-tree. When the enemy is dead, the entity wants to return to the path, which requires some re-pathing now (since walking towards the enemy might have made the current path un-optimal). This could happen in the "resume" function. 

Currently I would have to implement this by checking (every time the tree is processed), if the entity is still on the current path (by checking if the entity is still inside the current polygon of the nav mesh) or if it has diverged from it too much. This is wasted performance.

Also note that this is just one example. I actually think there will be many more concrete cases where I could use this type of decorator in the library.

About implementation: Every time the tree is processed, you could increment some hidden counter variable after each evaluation of the behavior tree. A node has been executing continuously and uninterrupted if the counter c_n is equal to c_(n-1)+1 when the node is executing, and has been interrupted if c is something else. 

edit: By the way, great library and great editor. Easy to use and extend.

**Comment by renatopp** [comment]
If I understood correctly, the current architecture provides a solution for you.

Internally, a node holds its state as OPEN or CLOSED. This state is useful to control which methods will be called when the node is executed at some frame. Any given node has 5 methods that can be called during its execution (they are called in this order, most of the time):
- **enter**: at the beginning of every execution.
- **open**: after "enter" and only if the node is closed. This changes the node state to OPEN.
- **tick**: called every execution, it is where the node will perform the computation needed to achieve its goal.
- **close**: called only if the node returned FAILURE, SUCCESS or ERROR as result of the tick method (it means that, if the tick returned RUNNING, the node is still open and waiting for the next tick cycle). This method changes the node state to CLOSED. Notice that, the BT still can call this method outside of the tick cycle, if in a future tick another node with more priority interrupts the execution of this node.
- **exit**: called at the end of every execution (after tick method has returned and after the close method, if called).

Note: I call execution the process of propagating the tick signal to a node.

**Example**:

Suppose you have this subtree with the node "Walk to goal" (lets refer to it simply by "walk"). This node is closed by default, so in the first tick this node is executed, the following methods are called:
1. enter
2. open
3. tick
4. exit

considering that the "walk" node returned RUNNING.

So, next tick the node is called again:
1. enter
2. tick
3. exit

Returning RUNNING again.

In a third tick, the "walk" node is interrupted by a "Attack enemy" node. Due to this interruption, the BT will call the `close` method of "walk".

So, in your case, you would implement the "walk" node like:

```
WalkAction:
  open:
    // compute path to the goal

  tick:
    // follow path to the goal
```

---

Sorry for the big answer, we still lack proper documentation to link this explanation. If this is still not what you need, please provide an sample implementation.

Thanks for the feedback o/

**Comment by TravisGesslein** [comment]
Thanks for the answer!

Yes, it seems that behavior can be perfectly implemented using the existing mechanics. It wasn't clear to me that close() is also called when a node is basically "interrupted". Thanks again, this will solve my problem.

**Comment by renatopp** [comment]
Great! Usually, other BT libraries implement nodes as simple functions. I decided to represent nodes with a bit more complex structure in order to handle things like this. 

After 0.2.0 release, I'll focus on the documentation and I hope to include all these subtleties of the library.
